services:
  - type: web
    name: fastapi-vite-app
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r backend/requirements.txt && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: uvicorn backend.app.main:app --host=0.0.0.0 --port=8000
    autoDeploy: true
